server.port=8089
server.servlet.contextPath=/payment
spring.profiles.active=${PROFILE:local}
spring.datasource.url=jdbc:mysql://localhost:3306/paymentDb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Khasim@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.ddl-auto=update
payment.webhook.secret=FLIPKART_SECRET_2026

# Actuator base path
management.endpoints.web.base-path=/actuator

# Expose specific endpoints
management.endpoints.web.exposure.include=health,info,metrics,loggers,threaddump,heapdump


# Enable all endpoints
management.endpoints.enabled-by-default=true